name: Checkout, Build, and Test

on: [push]

jobs:
  build:
    name: checkout, build, and test
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chisel3-tools
      options: --user root --entrypoint /bin/bash

    steps:
      - name: id
        run: |
          printenv
          whoami
          git --version
          pwd
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: chisel-iotesters
      - name: Cache SBT ivy cache
        id: cache-sbt-ivy-cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/*.sbt') }}
      - name: Cache SBT
        id: cache-sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/*.sbt') }}
      - name: Cache firrtl 2.11
        id: cache-firrtl-2_11
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/firrtl_2.11
          key: ${{ runner.os }}-sbt-${{ hashFiles('firrtl/build.sbt') }}-${{ hashFiles('firrtl/project/build.properties') }}-${{ hashFiles('firrtl/project/*.sbt') }}
      - name: Cache firrtl 2.12
        id: cache-firrtl-2_12
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/firrtl_2.12
          key: ${{ runner.os }}-sbt-${{ hashFiles('firrtl/build.sbt') }}-${{ hashFiles('firrtl/project/build.properties') }}-${{ hashFiles('firrtl/project/*.sbt') }}
      - name: Build FIRRTL
        id: build-firrtl
        if: steps.cache-firrtl-2_11.outputs.cache-hit != 'true' || steps.cache-firrtl-2_12.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/freechipsproject/firrtl.git
          cd firrtl && sbt +publishLocal
      - name: Cache chisel3 2.11
        id: cache-chisel3-2_11
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/chisel3_2.11
          key: ${{ runner.os }}-sbt-${{ hashFiles('chisel3/build.sbt') }}-${{ hashFiles('chisel3/project/build.properties') }}-${{ hashFiles('chisel3/project/*.sbt') }}
      - name: Cache chisel3 2.12
        id: cache-chisel3-2_12
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/chisel3_2.12
          key: ${{ runner.os }}-sbt-${{ hashFiles('chisel3/build.sbt') }}-${{ hashFiles('chisel3/project/build.properties') }}-${{ hashFiles('chisel3/project/*.sbt') }}
      - name: Build chisel3
        id: build-chisel3
        if: steps.cache-chisel3-2_11.outputs.cache-hit != 'true' || steps.cache-chisel3-2_12.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/freechipsproject/chisel3.git
          cd chisel3 && sbt +publishLocal
      - name: Build and test iotesters
        id: build-test-iotesters
        run: |
          cd chisel-iotesters && sbt +test
