name: Checkout, Build, and Test

on: [push]

jobs:
  build:
    name: checkout, build, and test
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chisel3-tools
      options: --user root --entrypoint /bin/bash
    env:
      CHISEL3_REF: master
      FIRRTL_REF: master
      FIRRTL_INTERPRETER_REF: master
      TREADLE_REF: master

    steps:
      - name: id
        run: |
          printenv
          whoami
          git --version
          pwd
          echo "tilde: " ~ ", HOME: " $HOME
          ls -lad $HOME
          ls -la $HOME /root
          if [ `id -u` == "0" ]; then echo "Link /root caches to HOME"; mkdir -p $HOME/.ivy2 $HOME/.sbt; ln -s $HOME/.ivy2 $HOME/.sbt /root; fi
          ls -la  /root $HOME .
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: chisel-iotesters
      - name: Generate SBT SHA1s
        id: gen-sbt-shas
        run: |
          ls -la . chisel-iotesters
          (cd chisel-iotesters && openssl sha1 build.sbt project/build.properties project/*.sbt) > sbt.hashes
      - name: Cache SBT ivy cache
        id: cache-sbt-ivy-cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('sbt.hashes') }}
      - name: Cache SBT
        id: cache-sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('sbt.hashes') }}
      - name: Generate dependend SHA1s
        id: gen-independent-shas
        run: |
          echo ::set-env name=FIRRTL_SHA::$(git ls-remote https://github.com/freechipsproject/firrtl.git | grep $FIRRTL_REF | cut -c1-7)
          echo ::set-env name=CHISEL3_SHA::$(git ls-remote https://github.com/freechipsproject/chisel3.git | grep $CHISEL3_REF | cut -c1-7)
          echo ::set-env name=FIRRTL_INTERPRETER_SHA::$(git ls-remote https://github.com/freechipsproject/firrtl-interpreter.git | grep $FIRRTL_INTERPRETER_REF | cut -c1-7)
          echo ::set-env name=TREADLE_SHA::$(git ls-remote https://github.com/freechipsproject/treadle.git | grep $TREADLE_REF | cut -c1-7)
      - name: Cache firrtl 2.11
        id: cache-firrtl-2_11
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/firrtl_2.11
          key: ${{ runner.os }}-sbt-firrtl-${{ env.FIRRTL_SHA }}
      - name: Cache firrtl 2.12
        id: cache-firrtl-2_12
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/firrtl_2.12
          key: ${{ runner.os }}-sbt-firrtl-${{ env.FIRRTL_SHA }}
      - name: Build FIRRTL
        id: build-firrtl
        if: steps.cache-firrtl-2_11.outputs.cache-hit != 'true' || steps.cache-firrtl-2_12.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 -b $FIRRTL_REF https://github.com/freechipsproject/firrtl.git
          cd firrtl && sbt +publishLocal
      - name: Cache firrtl-interpreter 2.11
        id: cache-firrtl-interpreter-2_11
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/firrtl-interpreter_2.11
          key: ${{ runner.os }}-sbt-firrtl-interpreter-${{ env.FIRRTL_INTERPRETER_SHA }}
      - name: Cache firrtl-interpreter 2.12
        id: cache-firrtl-interpreter-2_12
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/firrtl-interpreter_2.12
          key: ${{ runner.os }}-sbt-firrtl-interpreter-${{ env.FIRRTL_INTERPRETER_SHA }}
      - name: Build FIRRTL-interpreter
        id: build-firrtl-interpreter
        if: steps.cache-firrtl-interpreter-2_11.outputs.cache-hit != 'true' || steps.cache-firrtl-interpreter-2_12.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 -b $FIRRTL_INTERPRETER_REF https://github.com/freechipsproject/firrtl-interpreter.git
          cd firrtl-interpreter && sbt +publishLocal
      - name: Cache treadle 2.11
        id: cache-treadle-2_11
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/treadle_2.11
          key: ${{ runner.os }}-sbt-treadle-${{ env.TREADLE_SHA }}
      - name: Cache treadle 2.12
        id: cache-treadle-2_12
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/treadle_2.12
          key: ${{ runner.os }}-sbt-treadle-${{ env.TREADLE_SHA }}
      - name: Build treadle
        id: build-treadle
        if: steps.cache-treadle-2_11.outputs.cache-hit != 'true' || steps.cache-treadle-2_12.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 -b $TREADLE_REF https://github.com/freechipsproject/treadle.git
          cd treadle && sbt +publishLocal
      - name: Cache chisel3 2.11
        id: cache-chisel3-2_11
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/chisel3_2.11
          key: ${{ runner.os }}-sbt-chisel3-${{ env.CHISEL3_SHA }}
      - name: Cache chisel3 2.12
        id: cache-chisel3-2_12
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/edu.berkeley.cs/chisel3_2.12
          key: ${{ runner.os }}-sbt-chisel3-${{ env.CHISEL3_SHA }}
      - name: Build chisel3
        id: build-chisel3
        if: steps.cache-chisel3-2_11.outputs.cache-hit != 'true' || steps.cache-chisel3-2_12.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 -b $CHISEL3_REF https://github.com/freechipsproject/chisel3.git
          cd chisel3 && sbt +publishLocal
      - name: Build and test iotesters
        id: build-test-iotesters
        run: |
          cd chisel-iotesters && sbt +test
          chmod -R a+r . $HOME/.sbt $HOME/.ivy2
          ls -la . $HOME
